### ISSUE TITLE
Fails to load multiple resources of the same time.

### ISSUE THREAD

**Issue by nelg** [virtuald/pyhcl#12]
The following TF is not loaded correctly.  It does not create the first resource in the output json.

sampleinput.tf

<pre>
resource "aws_db_instance" "mysqldb" {
    identifier = "${var.environment}-mysqldb"
    allocated_storage = 100
}
resource "aws_db_instance" "mysqldb-readonly" {
    identifier = "${var.environment}-mysqldb-readonly"
    allocated_storage = 100
}
</pre>

JSON Output is:

<pre>
{
    "resource": {
        "aws_db_instance": {
            "mysqldb-readonly": {
                "allocated_storage": 100,
                "identifier": "${var.environment}-mysqldb-readonly"
            }
        }
    }
}
</pre>

Expected:

<pre>
{
    "resource": {
        "aws_db_instance": {
           "mysqldb": {
                "allocated_storage": 100,
                "identifier": "${var.environment}-mysqldb"
            },
            "mysqldb-readonly": {
                "allocated_storage": 100,
                "identifier": "${var.environment}-mysqldb-readonly"
            }
        }
    }
}
</pre>

**Comment by virtuald** [comment]
This seems related to #11 . Feel free to fix it and submit a pull request.

**Comment by nelg** [comment]
I would but not sure how to fix it, and have limited time to do so.

Glen

**Comment by virtuald** [comment]
I don't use terraform, and have limited time to fix this bug also.

**Comment by robeden** [comment]
Fixed somewhere along the line in PR #68 or before. That PR enables the unit test.
