### ISSUE TITLE
Unable to express list of maps as a literal in variables

### ISSUE THREAD

**Issue by w-miller** [virtuald/pyhcl#29]
A list of maps, such as the minimal test case below, should be parsed successfully, however an error occurs when attempting to parse such a structure with PyHCL.

sampleinput.tf:
```
resource = [{
    foo = [{
        bar = {}
    }]
}]
```
Output (PyHCL 0.3.6):
`
ValueError: Line 1, column 12: unexpected LEFTBRACE
`

This issue was [reported and fixed](https://github.com/hashicorp/terraform/issues/7142) for the golang parser last year. Test case [assign_deep.hcl](https://github.com/hashicorp/hcl/blob/master/test-fixtures/assign_deep.hcl) tests this structure, and for the golang parser this snippet is marked as [valid](https://github.com/hashicorp/hcl/blob/master/decoder_test.go#L230). The same test case exists for PyHCL, however the [same snippet](https://github.com/virtuald/pyhcl/blob/master/tests/lex-fixtures/assign_deep.hcl) is marked as [invalid](https://github.com/virtuald/pyhcl/blob/master/tests/test_parser.py#L49), meaning the test case appears to pass.

**Comment by virtuald** [comment]
Closed via #30
