### ISSUE TITLE
Variables interpolation 

### ISSUE THREAD

**Issue by Ar1k14001** [virtuald/pyhcl#59]
The original hcl implement variables interpolation like in the below example:

`provider "linode" { `
`    token = "${var.token}" }`

pyhcl however doesn't implement it and the value given by parsing in `"${var.token}"` instead of the token itself.
Please fix this incompatible parsing.

**Comment by virtuald** [comment]
Terraform performs application-specific interpolation, that isn't a function of the hcl language.
