### ISSUE TITLE
Parser debug hard-coded to on since "export comments" merged.

### ISSUE THREAD

**Issue by fred-vogt** [virtuald/pyhcl#66]
It would seem that [optional export code comments](https://github.com/virtuald/pyhcl/commit/a34ff30682a18b3f0dd353a450e899f0509671e1#diff-a28c13c8319776e20d180bfc5c31bc78) left `debug=True` when parsing.

#65 fixes it.

```python
def parse(self, s):
      return self.yacc.parse(s, lexer=Lexer())
# => 
def parse(self, s, export_comments=None):
    return self.yacc.parse(s, lexer=Lexer(export_comments=export_comments), debug=True)
```

## Workaround
Use version 0.4.0 or older.

requirements.txt:
```
pyhcl==0.4.0
```

## Output
```
PLY: PARSE DEBUG START

State  : 0
Stack  : . LexToken(IDENTIFIER,'...',...)
Action : Shift and goto state 7
```

**Comment by robeden** [comment]
@virtuald - This can be closed. Looks like it was fixed in PR #65.
