### ISSUE TITLE
WARNING: Token 'COMMAEND' defined, but not used

### ISSUE THREAD

**Issue by raymondbutcher** [virtuald/pyhcl#69]
Hi, with 0.4.3 I see this printed out a lot:

```
WARNING: Token 'COMMAEND' defined, but not used
WARNING: There is 1 unused token
```

Downgrading to 0.4.2 fixes it.

#68 was the only difference between those 2 versions so it's likely something in there.

**Comment by robeden** [comment]
I’ll take a look.
