### ISSUE TITLE
dependent terraform resources

### ISSUE THREAD

**Issue by farchide** [virtuald/pyhcl#76]
How to use the pyhcl when we have dependent resources in a terraform file?
for example, let's say we have a vpc resource, and then on then next resource we want to use vpc id to assign it.

pyhcl gives us an error in this situation since the vpc id is not defined and it is not  in the variables. but the terraform code is totally fine and we can execute it with no error.

**Comment by virtuald** [comment]
pyhcl is not a terraform library, it is an HCL1 library. That sounds potentially like HCL2 functionality, recommend trying pyhcl2.
