### ISSUE TITLE
Support for array of objects

### ISSUE THREAD

**Issue by akshaypatidar1999** [virtuald/pyhcl#83]
I am using an array of objects as they are supported in terraform but the current implementation is not able to parse this.
```
cluster_parameters                  = [{'name': 'neptune_enforce_ssl', 'value': '0', 'apply_method': 'pending-reboot'}]
```

It would be great if this can be added in future versions

**Comment by virtuald** [comment]
I believe this is an HCL2 feature. From the README:

> pyhcl does not support HCL2 (which is what modern terraform uses). You might try https://pypi.org/project/python-hcl2/ instead (though I've never personally tried it).
